pathMensajes = data/mensajes.json
pathMensajesPrivados = data/mensajesPrivados.json
pathGrupos = data/grupos.json
pathUsuarios = data/usuarios.json
keyStorePassword = accesoKeyStore
keyStorePath = keyStore/keystore.jks