###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "user",
  "password": "1234"
}

> {%
    client.global.set("token", response.body);
%}


###
GET http://localhost:8080/tierras/getAll

###
GET http://localhost:8080/tierras/getAll

###
GET http://localhost:8080/tierras/getAllSinCultivos

###
PUT http://localhost:8080/tierras/add
Content-Type: application/json

{
  "lat": "123",
  "lng": "123",
  "metros": 1000,
  "cultivos": []
}

###
GET http://localhost:8080/cultivos/get
Content-Type: application/json

{
  "nombre": "sadas",
  "valorEnergetico": 10,
  "caracteristicas": "asddsa",
  "tierras": []
}

###
PUT http://localhost:8080/cultivos/add
Content-Type: application/json

{
  "nombre": "gfdgfdg",
  "valorEnergetico": 10,
  "caracteristicas": "gfdgdfg",
  "tierras": []
}
