###
POST http://localhost:8080/signUp?email=jane@example.com&password=1234

<> 2025-02-10T223914.201.txt
<> 2025-02-10T180150.201.txt
<> 2025-02-10T175015.201.txt
<> 2025-02-10T174358.201.txt
<> 2025-02-10T173945.405.json

###
GET http://localhost:8080/confirm?
    code=HrlEoQg1PtYy99lliVQaBw==__;!!D9dNQwwGXtA!XsUiQbw-EXfWYyh50pNYE0wg3XK_XLU7CDiYbhWAy2PcUy2NBkq3JvTp_R0Bmycj0rLRAwu9t91UeFYia5qS5465g2ayFAQ1U-g$

<> 2025-02-10T224000.202.txt
<> 2025-02-10T180121.202.txt
<> 2025-02-10T180103.202.txt

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "1234"
}

> {%
    client.global.set("token", response.body.login);
%}

<> 2025-02-10T224044.200.txt
<> 2025-02-10T180253.200.txt
<> 2025-02-10T174627.200.txt
<> 2025-02-10T174441.200.txt
<> 2025-02-10T173505.500.json
<> 2025-02-10T171053.500.jso


###
GET http://localhost:8080/playlists/getAll
Authorization: Bearer {{token}}
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/playlists/get
Authorization: Bearer {{token}}
Content-Type: application/json

3

###
DELETE http://localhost:8080/playlists/delete/3
Authorization: Bearer {{token}}

###
GET http://localhost:8080/songs/getAll
Authorization: Bearer {{token}}
