spring.application.name=Examen2evaJorgeNovillo2


#a day
#application.security.jwt.expiration=86400000
application.security.jwt.expiration=30
#7 days
application.security.jwt.refresh-token.expiration=604800000
