package org.example.appmensajessecretos.domain.error;

public enum ServiceError implements Error{
    GROUP_NOT_FOUND,
    NOT_IN_GROUP,
    NOT_IN_GROUPS,
    USER_NOT_FOUND,
    GROUP_ALREADY_EXISTS,
    ERROR_SENDING_MESSAGE,
    ERROR_JOINING_GROUP,
    USER_ALREADY_EXIST,
    ERROR_ENCRYPTING,
    ERROR_DECRYPTING,
    ALREADY_IN_GROUP,
    ERROR_GENERATING_KEYS,
    ERROR_COMPLETING_TASK,
    GROUP_HAS_NO_MESSAGES, ERROR_GETTING_PUBLIC_KEY, ERROR_GETTING_PRIVATE_KEY,
}
